# general settings
name: train_RealDAT_x4_bs4_srclip
model_type: RealDATModel
scale: 4
num_gpu: auto
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: LSDIR
    type: PairedImageDataset_LSDIR
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR
    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_real/X4
    meta_info: datasets/LSDIR/data/srclip_train.csv
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 12
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    task: SR
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_valid_HR
    dataroot_lq: datasets/DIV2K/DIV2K_valid_LR_real/X4
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: RealDAT
  upscale: 4
  in_chans: 3
  img_size: 64
  img_range: 1.
  split_size: [8,32]
  depth: [6,6,6,6,6,6]
  embed_dim: 180
  num_heads: [6,6,6,6,6,6]
  expansion_factor: 4
  resi_connection: '1conv'
  fusion_layers: 'all'

network_clip:
  type: srclipv2_ViT-B-32

# path
path:
  pretrain_network_g: experiments/train_RealDAT_x2_bs4_srclip3/models/net_g_350000.pth
  srclip_pretrain_network: logs/srclipv2_ViT-B-32_siglip_b512x1_lr2e-5_e100_fix_exp1/checkpoints/epoch_30.pt
  strict_load_g: False
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e4
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: True

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
